// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5fGc0Wx-n602_RMwlWfp3gMHOCei5qfE',
    appId: '1:783186713443:web:20ad7eb793eaf16b1c1156',
    messagingSenderId: '783186713443',
    projectId: 'resturants-8709f',
    authDomain: 'resturants-8709f.firebaseapp.com',
    storageBucket: 'resturants-8709f.firebasestorage.app',
    measurementId: 'G-D6BHHZFEXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD892aJCft4CHWJN3K59HOODczfccLSNXg',
    appId: '1:783186713443:android:dab93e1d210f7bad1c1156',
    messagingSenderId: '783186713443',
    projectId: 'resturants-8709f',
    storageBucket: 'resturants-8709f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvVGX-QFTfdxOCtkTWyTksUqvswQcYj-I',
    appId: '1:783186713443:ios:9d6f532cb02ab5ff1c1156',
    messagingSenderId: '783186713443',
    projectId: 'resturants-8709f',
    storageBucket: 'resturants-8709f.firebasestorage.app',
    iosBundleId: 'com.example.resturantsDel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvVGX-QFTfdxOCtkTWyTksUqvswQcYj-I',
    appId: '1:783186713443:ios:9d6f532cb02ab5ff1c1156',
    messagingSenderId: '783186713443',
    projectId: 'resturants-8709f',
    storageBucket: 'resturants-8709f.firebasestorage.app',
    iosBundleId: 'com.example.resturantsDel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5fGc0Wx-n602_RMwlWfp3gMHOCei5qfE',
    appId: '1:783186713443:web:75cb8f5ac7f5738e1c1156',
    messagingSenderId: '783186713443',
    projectId: 'resturants-8709f',
    authDomain: 'resturants-8709f.firebaseapp.com',
    storageBucket: 'resturants-8709f.firebasestorage.app',
    measurementId: 'G-QSV15EKP66',
  );
}
